### ISSUE TITLE
Webform instead of contact forms

### ISSUE THREAD

**Issue by zietbukuel** [droptica/droopler_project#92]
It would be nice to have webforms instead of contact forms. Webform provides more power and flexibility and it's just better because it provides many types of integrations, conditions, etc etc.

So, I changed the referenced entity from contact form to webforms but when I add a form to a page it's showing a contact form? I've looked at the code for d_p_form and there doesn't seem to be anything that forces contact forms to be embedded instead of webforms.

I'm using the latest Droopler release 8.2.0.

**Comment by Amstercad** [comment]
I can't help but strongly disagree with the use of webforms, because when stakeholder requirements become advanced, as they always do, one finds they've already gone down a rabbit-hole of fail. Which is why I argue Contact Forms is sufficient for the Droopler Distribution, (why throw less experienced developers down a rabbithole with Webforms promotion by inclusion?).

For those folks that don't know what I am talking about, [may I please refer you to this well-written article](https://www.gizra.com/content/form-modes-wizard-drupal-8/) and documented code-example.

And think about it, have you ever seen [a Drupal Form coded properly using FormAPI](https://www.drupal.org/node/717732) as Gizra documented? If not, imagine stakeholder changes arriving long after the initial development and how cheap and easy they are to implement in code, and how clearly changes reveal themselves using simple color-coded GIT, and all that value.

Not to mention how developing in-house experience writing & editing form code by hand as documented creates easily re-usable in-house copy/paste templates of form code to reduce future costs.

**Comment by grzegorz-pietrzak-droptica** [comment]
We won't introduce support for Webform in the nearest future, however, in the current 3.0 release we are making sure that the module throw no errors while being used inside Droopler's paragraphs.
